### ISSUE TITLE
SQLCU url is broken

### ISSUE THREAD

**Issue by mclasson** [HealisticEngineer/Docker#1]
Change it to https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5001090-x64.exe
Then it works again.
Thanks for the image.

**Comment by HealisticEngineer** [comment]
Thanks for that haven't used it in few months.
It's updated and should now be working till next CU release :)

**Comment by mclasson** [comment]
:-)
Another issue I have is cross-AD auth from PBI. Did you get that to work? Because the container one is using some random AD it seems. What's your thoughts on that?

**Comment by HealisticEngineer** [comment]
That kind of depends on what the container is running on as you can use group managed service accounts so that the container can use the gMSA to access the AD accounts.

Since both Kubernetes and Docker support having a windows worker it should be possible to do as long as your Admin is willing to have a windows worker.

Reference:
https://www.youtube.com/watch?v=qiV_2mWgjUY&list=PLz99tsDa7uF8_kdq-7WJfpWo3BWV7T92m&index=7

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts

**Comment by nixiam** [comment]
Hi,
the url is broken again

**Comment by HealisticEngineer** [comment]
> Hi, the url is broken again

updated again ;) if i get sometime I'll try to make it dynamic so that updates each time

**Comment by nixiam** [comment]
> > Hi, the url is broken again
> 
> updated again ;) if i get sometime I'll try to make it dynamic so that updates each time

Thank's!

Is there a possibility to make it work with linux / arm?

**Comment by HealisticEngineer** [comment]
While SQL Server these days can run on Linux and even ARM I guess, PowerBI Report Server doesn't have a Linux version, mostly because of the heavy.NET dependencies.  I don't believe the Microsoft product team plan to change that.

**Comment by HealisticEngineer** [comment]
Both the SQL Server CU and the PowerBI Report Server have been converted to a dynamic version.
They will always download the latest version
