### ISSUE TITLE
Cannot upload pbix reports

### ISSUE THREAD

**Issue by nfire11** [HealisticEngineer/Docker#2]
The web portal works but fail to upload pbix files (but can upload csv, spreadsheets):
"There was an error uploading your .pbix file. Verify that the file has not been corrupted and that the file extension matches the format of the file."

The desktop version & report server matches (Jan. 21).
Found the following record in RSPortal logfiles when upload pbix files
2021-05-27 21:31:11.8910|ERROR|56|The remote server returned an error: (404) Not Found.| RequestID = s_1f932cc9-4104-44c4-9561-32cdc5e85900

**Comment by HealisticEngineer** [comment]
You might want to check the build numbers as I know Microsoft has had some issues in the past and done releases with the same name (Jan .21) for example but the build number changes.  They had something like this in the (April 20).

Anyway, there is now a (May 21) release so that likely fixes the problem.
